import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'WebShopX',
      link: {type: 'doc', id: 'webshopx/webshopx-overview'},
      items: [
        {
          type: 'category',
          label: '开始使用',
          link: {type: 'doc', id: 'webshopx/player/quick-start'},
          items: [
            {type: 'doc', id: 'webshopx/player/quick-start'},
            {type: 'doc', id: 'webshopx/admin/install-deploy'},
            {type: 'doc', id: 'webshopx/admin/v2-to-v3-migration'},
          ],
        },
        {
          type: 'category',
          label: '使用指南',
          link: {type: 'doc', id: 'webshopx/guides/guides-overview'},
          items: [
            {type: 'doc', id: 'webshopx/player/shop-and-orders'},
            {type: 'doc', id: 'webshopx/player/wallet-and-exchange'},
            {type: 'doc', id: 'webshopx/guides/inventory-and-delivery'},
            {type: 'doc', id: 'webshopx/guides/auctions-and-pricing'},
            {type: 'doc', id: 'webshopx/player/faq'},
            {
              type: 'category',
              label: '深入了解',
              collapsed: true,
              items: [
                {type: 'doc', id: 'webshopx/player/inventory'},
                {type: 'doc', id: 'webshopx/player/claim-and-mailbox'},
                {type: 'doc', id: 'webshopx/player/auctions'},
                {type: 'doc', id: 'webshopx/player/dynamic-pricing'},
                {type: 'doc', id: 'webshopx/player/limits'},
                {type: 'doc', id: 'webshopx/player/algorithm'},
              ],
            },
          ],
        },
        {
          type: 'category',
          label: '服务器管理',
          link: {type: 'doc', id: 'webshopx/admin/overview'},
          items: [
            {type: 'doc', id: 'webshopx/admin/configuration'},
            {type: 'doc', id: 'webshopx/admin/governance'},
            {type: 'doc', id: 'webshopx/admin/operations'},
            {type: 'doc', id: 'webshopx/admin/faq'},
            {
              type: 'category',
              label: '高级专题',
              collapsed: true,
              items: [
                {type: 'doc', id: 'webshopx/admin/relay-access'},
                {type: 'doc', id: 'webshopx/admin/inventory-operations'},
                {type: 'doc', id: 'webshopx/admin/delivery-refund-ops'},
                {type: 'doc', id: 'webshopx/admin/visual-resources'},
              ],
            },
          ],
        },
        {
          type: 'category',
          label: '开发',
          link: {type: 'doc', id: 'webshopx/developer/developer-quickstart'},
          items: [
            {type: 'doc', id: 'webshopx/developer/developer-quickstart'},
            {type: 'doc', id: 'webshopx/developer/player-api'},
            {type: 'doc', id: 'webshopx/developer/market-api'},
            {type: 'doc', id: 'webshopx/developer/admin-api'},
            {type: 'doc', id: 'webshopx/webshopx-payment-api'},
            {
              type: 'category',
              label: '专题参考',
              collapsed: true,
              items: [
                {type: 'doc', id: 'webshopx/developer/api-basics'},
                {type: 'doc', id: 'webshopx/developer/authentication'},
                {type: 'doc', id: 'webshopx/developer/errors-and-idempotency'},
                {type: 'doc', id: 'webshopx/developer/uploads-and-static-assets'},
                {type: 'doc', id: 'webshopx/developer/integration-playbook'},
              ],
            },
          ],
        },
        {
          type: 'category',
          label: '参考',
          link: {type: 'doc', id: 'webshopx/reference/overview'},
          items: [
            {type: 'doc', id: 'webshopx/admin/commands-permissions'},
            {type: 'doc', id: 'webshopx/reference/http-api-reference'},
            {type: 'doc', id: 'webshopx/player/glossary'},
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'WebShopX-Payments',
      link: {type: 'doc', id: 'webshopx-payments/overview'},
      items: [{type: 'autogenerated', dirName: 'webshopx-payments'}],
    },
  ],
};

export default sidebars;
