import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const currentLocale = process.env.DOCUSAURUS_CURRENT_LOCALE ?? 'zh-CN';
const isZh = currentLocale === 'zh-CN';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'WebShopX',
      link: {
        type: 'generated-index',
        title: 'WebShopX',
        description: isZh
          ? '从快速上手到运营、二次开发与精确参考。'
          : 'From first use to operations, development, and precise reference.',
        slug: '/category/webshopx',
      },
      items: [
        {type: 'doc', id: 'webshopx/webshopx-overview'},
        {
          type: 'category',
          label: isZh ? 'Get started · 开始使用' : 'Get started',
          link: {
            type: 'generated-index',
            title: isZh ? '开始使用 WebShopX' : 'Get started with WebShopX',
            description: isZh
              ? '第一次使用、第一次部署或从旧版本迁移，从这里开始。'
              : 'Start here for first use, first deployment, or migration.',
            slug: '/category/webshopx-get-started',
          },
          items: [
            {type: 'doc', id: 'webshopx/player/quick-start'},
            {type: 'doc', id: 'webshopx/admin/install-deploy'},
            {type: 'doc', id: 'webshopx/admin/v2-to-v3-migration'},
          ],
        },
        {
          type: 'category',
          label: isZh ? 'Guides · 使用指南' : 'Guides',
          link: {
            type: 'doc',
            id: 'webshopx/guides/guides-overview',
          },
          items: [
            {type: 'doc', id: 'webshopx/player/shop-and-orders'},
            {type: 'doc', id: 'webshopx/player/wallet-and-exchange'},
            {type: 'doc', id: 'webshopx/guides/inventory-and-delivery'},
            {type: 'doc', id: 'webshopx/guides/auctions-and-pricing'},
            {type: 'doc', id: 'webshopx/player/faq'},
          ],
        },
        {
          type: 'category',
          label: isZh ? 'Administration · 服务器管理' : 'Administration',
          link: {
            type: 'generated-index',
            title: isZh ? '服务器管理' : 'Administration',
            description: isZh
              ? '部署后配置、市场治理、运维、安全与故障排查。'
              : 'Configuration, market governance, operations, security, and troubleshooting.',
            slug: '/category/webshopx-administration',
          },
          items: [
            {type: 'doc', id: 'webshopx/admin/configuration'},
            {type: 'doc', id: 'webshopx/admin/governance'},
            {type: 'doc', id: 'webshopx/admin/operations'},
            {type: 'doc', id: 'webshopx/admin/faq'},
          ],
        },
        {
          type: 'category',
          label: isZh ? 'Development · 开发' : 'Development',
          link: {
            type: 'generated-index',
            title: isZh ? 'WebShopX 开发' : 'WebShopX Development',
            description: isZh
              ? '快速接入 HTTP API，并继续深入 Player、Market、Admin 与支付 Provider。'
              : 'Quickly integrate the HTTP API, then continue with Player, Market, Admin, and payment providers.',
            slug: '/category/webshopx-development',
          },
          items: [
            {type: 'doc', id: 'webshopx/developer/developer-quickstart'},
            {type: 'doc', id: 'webshopx/developer/player-api'},
            {type: 'doc', id: 'webshopx/developer/market-api'},
            {type: 'doc', id: 'webshopx/developer/admin-api'},
            {type: 'doc', id: 'webshopx/webshopx-payment-api'},
          ],
        },
        {
          type: 'category',
          label: 'Reference',
          link: {
            type: 'doc',
            id: 'webshopx/reference/reference-overview',
          },
          items: [
            {type: 'doc', id: 'webshopx/admin/commands-permissions'},
            {type: 'doc', id: 'webshopx/reference/http-api-reference'},
            {type: 'doc', id: 'webshopx/player/glossary'},
          ],
        },
      ],
    },
    {
      type: 'category',
      label: isZh ? 'WebShopX-Payments' : 'WebShopX Payments',
      link: {
        type: 'generated-index',
        title: isZh ? 'WebShopX-Payments' : 'WebShopX Payments',
        description: isZh
          ? 'WebShopX 的独立支付扩展插件：安装、配置、支付渠道与常见问题。'
          : 'The standalone payment extension for WebShopX: installation, configuration, channels, and FAQ.',
        slug: '/category/webshopx-payments',
      },
      items: [{type: 'autogenerated', dirName: 'webshopx-payments'}],
    },
  ],
};

export default sidebars;
